version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ipul/apkbukutamu
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    networks:
      - laravelnet
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_DATABASE:-laravel}
      DB_PASSWORD:  ${DB_PASSWORD:-password}

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_DATABASE:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravelnet

networks:
  laravelnet:
    driver: bridge

volumes:
  dbdata:
